export const OBSERVABILITY_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Relay Observability</title><style>
:root{color-scheme:dark;--bg:#0b1020;--panel:#151c30;--muted:#9aa8c7;--line:#2b3653;--accent:#72d6b3}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#edf3ff;font:14px system-ui,sans-serif}main{max-width:900px;margin:auto;padding:24px}header{display:flex;gap:18px;align-items:center;flex-wrap:wrap;margin-bottom:24px}h1{margin:0;font-size:26px}header span{color:var(--muted)}button{margin-left:auto;background:var(--accent);border:0;border-radius:7px;padding:10px 14px;font-weight:700;cursor:pointer}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card,section{background:var(--panel);border:1px solid var(--line);border-radius:10px}.card{padding:15px}.card b{display:block;font-size:23px;margin-top:7px}.card span{color:var(--muted)}section{margin-top:18px;padding:16px;overflow:auto}h2{font-size:17px;margin:0 0 12px}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{text-align:left;border-bottom:1px solid var(--line);padding:9px}th{color:var(--muted);font-size:12px}@media(max-width:600px){main{padding:14px}button{margin-left:0}}
</style></head><body><main><header><h1>AI Relay</h1><span id="uptime">Starting…</span><span id="refreshed"></span><button onclick="location.href='/observability/logs'">Download logs</button></header><div class="cards" id="cards"></div><section><h2>Called models</h2><table id="models"></table></section></main><script>
const n=v=>Number(v||0).toLocaleString(), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function table(id,heads,rows){document.getElementById(id).innerHTML='<thead><tr>'+heads.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody>'}
async function refresh(){try{const s=await fetch('/observability/stats',{cache:'no-store'}).then(r=>r.json()),t=s.totals;document.getElementById('uptime').textContent='Up '+Math.floor(s.uptime_seconds/3600)+'h '+Math.floor(s.uptime_seconds%3600/60)+'m '+s.uptime_seconds%60+'s · since '+new Date(s.started_at).toLocaleString();document.getElementById('refreshed').textContent='Refreshed '+new Date().toLocaleTimeString();const cards=[['Model calls',n(t.attempts)],['Successful calls',n(t.successes)],['Failed calls',n(t.failedAttempts)]];document.getElementById('cards').innerHTML=cards.map(c=>'<div class="card"><span>'+c[0]+'</span><b>'+c[1]+'</b></div>').join('');const models=[...s.models].sort((a,b)=>b.attempts-a.attempts||a.id.localeCompare(b.id));table('models',['Model','Calls','Successes','Failures'],models.map(x=>[esc(x.id),n(x.attempts),n(x.successes),n(x.failedAttempts)]))}catch(e){document.getElementById('refreshed').textContent='Refresh failed'}finally{setTimeout(refresh,1000)}}refresh();
</script></body></html>`;
