import type { Provider, ProviderUsage } from "./providers/index.ts";

/**
 * Observability boundary:
 * - record facts generated by the relay itself; and
 * - record values that cross the generic Provider interface.
 *
 * Never inspect concrete provider implementations, transports, quota internals,
 * or provider-specific payloads for observability. If a fact is not available
 * through the Provider contract, it is intentionally outside relay observability.
 */

interface Counters {
  requests: number;
  successes: number;
  terminalFailures: number;
  cancellations: number;
  attempts: number;
  failedAttempts: number;
  routingInputTokens: number;
  upstreamInputTokens: number | null;
  upstreamOutputTokens: number | null;
  upstreamTotalTokens: number | null;
}

function counters(): Counters {
  return {
    requests: 0,
    successes: 0,
    terminalFailures: 0,
    cancellations: 0,
    attempts: 0,
    failedAttempts: 0,
    routingInputTokens: 0,
    upstreamInputTokens: null,
    upstreamOutputTokens: null,
    upstreamTotalTokens: null,
  };
}

function addObserved(current: number | null, value: number | undefined): number | null {
  return value === undefined ? current : (current ?? 0) + value;
}

export class Observability {
  readonly startedAt = Date.now();
  private peakQueueDepth = 0;
  private readonly totals = counters();
  private readonly providers = new Map<string, Counters>();
  private readonly models = new Map<string, Counters>();
  private readonly modelProviders = new Map<string, string>();
  private readonly requestedModels = new Map<string, number>();
  private readonly registeredProviders: readonly Provider[];

  constructor(registeredProviders: readonly Provider[]) {
    this.registeredProviders = registeredProviders;
    for (const provider of registeredProviders) {
      this.providers.set(provider.id, counters());
    }
  }

  request(requestedModel: string, queueDepth: number): void {
    this.totals.requests += 1;
    this.requestedModels.set(requestedModel, (this.requestedModels.get(requestedModel) ?? 0) + 1);
    this.peakQueueDepth = Math.max(this.peakQueueDepth, queueDepth);
  }

  private modelCounters(providerId: string, modelId: string): Counters {
    let value = this.models.get(modelId);
    if (!value) {
      value = counters();
      this.models.set(modelId, value);
    }
    this.modelProviders.set(modelId, providerId);
    return value;
  }

  attempt(providerId: string, modelId: string, inputTokens: number): void {
    const model = this.modelCounters(providerId, modelId);
    for (const item of [this.totals, this.providers.get(providerId), model]) {
      if (!item) continue;
      item.attempts += 1;
      item.routingInputTokens += inputTokens;
    }
  }

  failedAttempt(providerId: string, modelId: string): void {
    const model = this.models.get(modelId);
    for (const item of [this.totals, this.providers.get(providerId), model]) {
      if (item) item.failedAttempts += 1;
    }
  }

  success(providerId: string, modelId: string, usage?: ProviderUsage): void {
    const model = this.models.get(modelId);
    for (const item of [this.totals, this.providers.get(providerId), model]) {
      if (!item) continue;
      item.successes += 1;
      item.upstreamInputTokens = addObserved(item.upstreamInputTokens, usage?.inputTokens);
      item.upstreamOutputTokens = addObserved(item.upstreamOutputTokens, usage?.outputTokens);
      item.upstreamTotalTokens = addObserved(item.upstreamTotalTokens, usage?.totalTokens);
    }
  }

  terminalFailure(providerId?: string, modelId?: string): void {
    this.totals.terminalFailures += 1;
    if (providerId) this.providers.get(providerId)!.terminalFailures += 1;
    const model = modelId ? this.models.get(modelId) : undefined;
    if (model) model.terminalFailures += 1;
  }

  cancellation(): void {
    this.totals.cancellations += 1;
  }

  snapshot(currentQueueDepth: number): Record<string, unknown> {
    const now = Date.now();
    const status = new Map(this.registeredProviders.map((provider) => [provider.id, provider.status(now)]));
    const registeredModels = this.registeredProviders.flatMap((provider) => {
      const providerHealth = status.get(provider.id);
      return provider.listModels().map((model) => {
        const health = providerHealth?.models.find((candidate) => candidate.id === model.id);
        return {
          id: model.id,
          provider: provider.id,
          input_capacity_tokens: model.inputCapacityTokens,
          active: health?.active ?? 0,
          blocked_until: health?.blockedUntil ? new Date(health.blockedUntil).toISOString() : null,
          overflow_blocked_until: health?.overflowBlockedUntil ? new Date(health.overflowBlockedUntil).toISOString() : null,
        };
      });
    });
    const registeredModelById = new Map(registeredModels.map((model) => [model.id, model]));

    return {
      started_at: new Date(this.startedAt).toISOString(),
      uptime_seconds: Math.floor((now - this.startedAt) / 1000),
      queue: { current_depth: currentQueueDepth, peak_depth: this.peakQueueDepth },
      totals: { ...this.totals },
      providers: [...this.providers].map(([id, value]) => {
        const provider = this.registeredProviders.find((candidate) => candidate.id === id);
        const health = status.get(id);
        return {
          id,
          priority: provider?.priority ?? null,
          ...value,
          configured: health?.configured ?? false,
          blocked_until: health?.blockedUntil ? new Date(health.blockedUntil).toISOString() : null,
        };
      }),
      models: [...this.models].map(([id, value]) => {
        const providerId = this.modelProviders.get(id) ?? "unknown";
        const registered = registeredModelById.get(id);
        const health = status.get(providerId)?.models.find((model) => model.id === id);
        return {
          id,
          provider: providerId,
          input_capacity_tokens: registered?.input_capacity_tokens ?? null,
          ...value,
          active: health?.active ?? 0,
          blocked_until: health?.blockedUntil ? new Date(health.blockedUntil).toISOString() : null,
          overflow_blocked_until: health?.overflowBlockedUntil ? new Date(health.overflowBlockedUntil).toISOString() : null,
        };
      }),
      registered_models: registeredModels,
      requested_models: [...this.requestedModels].map(([model, requests]) => ({
        model,
        kind: model === "auto" ? "auto" : "explicit",
        requests,
      })),
    };
  }
}
